### ISSUE TITLE
User can search for a product

### ISSUE THREAD

**Issue by brandonechin** [brandonechin/Kalopsia#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a product that will `get` sneaker data from the database.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can use the search bar to search for brands or specific sneakers. The search will return a list of results.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/111926994/220173714-823f2c38-cede-4cc4-827e-f3095700b6f4.png)
![image](https://user-images.githubusercontent.com/111926994/220174022-501c0ca2-f0b9-4042-bbab-38bcef0b1817.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create a database that includes tables for Orders, Cart, Users, Sneaker and Inventory data
- [x] Update `data.sql` to populate the database with Sneaker and Inventory data
    - [x] Include productId, brand, model, sku, price and imageUrl
- [x] `npm run db:import` to import `data.sql`

### ☁️ Server Tasks

- [x] Update `server/index.js` to `get` all sneaker data from the database using `app.get`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the navbar and free shipping banner
- [x] Create an image carousel that will eventually direct users to specific sneaker brand results
- [x] Add sneaker images that will eventually direct users to the product page
- [x] Create a component for a footer
- [x] Create a modal that appears when user searches for sneakers
- [x] Create a results page that depicts all sneakers from search results

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
