### ISSUE TITLE
User can add to cart

### ISSUE THREAD

**Issue by brandonechin** [brandonechin/Kalopsia#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a product to their shopping cart.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on add to cart, the product will be placed in their shopping cart.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/111926994/220177317-9e107510-077d-40f4-befe-26ae5e0333f5.png)
![image](https://user-images.githubusercontent.com/111926994/220177589-b463703f-25fb-45c4-b6c3-25da56f4b69d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to insert product to cart items table, insert new cart and update inventory when user adds product to cart.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to for add to cart modal.
- [ ] Create add to cart page.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
